name: 'Tiny Flags Action'
description: 'Automatically update feature flags in your repository'
branding:
  icon: 'flag'  # Using the 'flag' icon from Feather icons
  color: 'blue' # GitHub supports: yellow, blue, green, orange, red, purple, or gray
inputs:
  flags_repo:
    description: 'Repository to store flags (format: owner/repo)'
    required: true
  pattern:
    description: 'Pattern to find feature flag files'
    default: '**/*FeatureFlag.swift'
    required: false
  token:
    description: 'GitHub token for flag repo access'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Parse and Update Flags
      shell: bash
      run: |
        # First clone the app repo into actions repo
        git clone https://x-access-token:${{ inputs.token }}@github.com/${{ inputs.flags_repo }} app-repo
        
        # Run parser to create feature_flags directory (in the actions repo)
        python3 ${{ github.action_path }}/flag-parser.py "${{ inputs.pattern }}"

        # Copy feature_flags into app repo from actions repo
        cp -r feature_flags app-repo/
        cd app-repo

        # Configure git and push changes
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add feature_flags
        git diff --quiet && git diff --staged --quiet || (
          git commit -m "Update flags" && 
          git push && 
          echo "::notice::Access feature flags at https://raw.githubusercontent.com/${{ inputs.flags_repo }}/main/feature_flags/{enum}FeatureFlag/{featureName}"
        )
