name: 'Feature Flag Parser'
description: 'Parse Swift Feature Flags and update flags repository'
inputs:
  flags_repo:
    description: 'Repository to store flags (format: owner/repo)'
    required: true
  pattern:
    description: 'Pattern to find feature flag files'
    default: '**/*FeatureFlag.swift'
    required: false
  token:
    description: 'GitHub token for flag repo access'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Run Parser
      shell: bash
      run: python3 ${{ github.action_path }}/flag-parser.py "${{ inputs.pattern }}" flags.json
    - name: Update Flags Repo
      shell: bash
      run: |
        git clone https://x-access-token:${{ inputs.token }}@github.com/${{ inputs.flags_repo }} flags-repo
        cp flags.json flags-repo/
        cd flags-repo
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add flags.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update flags" && git push)