name: 'Tiny Flags Action'
description: 'Automatically update feature flags in your repository'
branding:
  icon: 'flag'  # Using the 'flag' icon from Feather icons
  color: 'blue' # GitHub supports: yellow, blue, green, orange, red, purple, or gray
inputs:
  branch:
    description: 'Branch to store feature flags'
    default: 'generated_flag_branch'
    required: false
  token:
    description: 'GitHub token for flag repo access'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Updating feature flag branch
      shell: bash
      run: |
          # setup ID
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          # Check if the branch already exists
          if git show-ref --verify --quiet refs/heads/${{ inputs.branch }}; then
            git checkout ${{ inputs.branch }}
          else
            git checkout -b ${{ inputs.branch }}
          fi

          # Fetch the latest changes from the main branch
          git fetch origin main

          # Rebase the current branch with the main branch to solve conflicts
          git rebase origin/main

    - name: Syncing Feature Flags
      shell: bash
      run: |
          python3 ${{ github.action_path }}/flag-parser.py --input_dir . --output_dir ./generated_feature_flags --pattern '**/*FeatureFlag.swift'

    - name: Creating Viewing Page
      shell: bash
      run: |
          python3 ${{ github.action_path }}/html-parser.py --input ${{ github.action_path }}/index-template.html --output ./generated_feature_flags --flags flags.json --repo ${{ github.repository }} --branch ${{ inputs.branch }}

          # Add gh pages index
          rm -rf index.html
          cp ./generated_feature_flags/index.html index.html

    - name: Pushing Changes to branch
      shell: bash
      run: |
          # Add all changes
          git add ./generated_feature_flags && git commit -m "Update Feature Flags"
          git add index.html && git commit -m 'Update Github page'

          # Push changes to new branch
          git push --force https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }} HEAD
    
    - name: Print Link to Page
      shell: bash
      run: |
          # TODO: change this page to point to right place
          echo "::notice::Update pages to generated branch https://github.com/${{ github.repository }}/settings/pages"
          echo "::notice::Feature flags view is available at https://${{ github.repository_owner }}.github.io/${{ github.repository }}/"