name: Update Flags
on:
  push:
    paths: ['**/*FeatureFlag.swift']
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: lloydoad/tiny-flagging-action@v1.0.1
        with:
          flags_repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
