name: Update Flags
on:
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lloydoad/tiny-flagging-action@v1.0.1
        with:
          flags_repo: ${{ github.repository }}  # Uses current repo
          token: ${{ github.token }}  # Uses default token
