name: Update Flags
on:
  push:
    paths: ['**/feature_flags/**', '**/*FeatureFlag.swift']
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: lloydoad/tiny-flagging-action@v2
        with:
          flags_repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
