name: Update Flags
on:
  push:
    paths: ['**/*FeatureFlag.swift']
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lloydoad/tiny-flagging-action
        with:
          flags_repo: ${{ github.repository }}  # Uses current repo
          token: ${{ github.token }}  # Uses default token
